# Generated by Django 2.1.1 on 2018-10-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapi', '0003_auto_20180930_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestadorservico',
            old_name='padorrest',
            new_name='prestador',
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='data',
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='hora',
        ),
    ]
