# Generated by Django 2.1.1 on 2018-10-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapi', '0004_auto_20181010_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocao',
            old_name='imagem',
            new_name='imagem_promocao',
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagem_categoria',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='promocao',
            name='link_promocao',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
